### ISSUE TITLE
When a batch has been resumed (using --resume option), the formatting of the console messages are a bit messed up

### ISSUE THREAD

**Issue by PrajwalSD** [PrajwalSD/runSAS#3]
This was observed in a production environment. It seems like the skipped jobs are ill-formatted on the console (decorators are missing etc.) until it reaches a job that has previously failed. 

Not a major issue, as the core functionality is still uninterrupted and "batch" mode which is likely to be the case for the production environment this is not an issue.

**Comment by karolisbu** [comment]
Attaching screenshot
![image](https://user-images.githubusercontent.com/23307699/147761787-da70bf06-36ee-4ead-b24f-2317615bd14f.png)
